user-interviews/ui-design-system

- package.json
- yarn.lock
Closes #12 
Updates babel-preset-env package to the more recent scoped version. The old package used an old version of browserslist as a dependency which broke precompiling assets in the host app.
> UIDS-12 update babel-preset-env dependency

- .eslintrc
- .gitignore
- package.json
- scss/box_shadow.scss
- scss/navbar.scss
- scss/theme.scss
- spec/Flash/Flash.test.jsx
- spec/Flash/__snapshots__/withFlash.test.jsx.snap
- spec/Flash/useFlash.test.js
- spec/Flash/withFlash.test.jsx
- spec/__snapshots__/Storyshots.test.js.snap
- src/FadeTransition/FadeTransition.jsx
- src/FadeTransition/FadeTransition.scss
- src/Flash/Flash.jsx
- src/Flash/Flash.scss
- src/Flash/FlashMessage.jsx
- src/Flash/fade_transition/FadeTransition.jsx
- src/Flash/fade_transition/FadeTransition.scss
- src/Flash/index.js
- src/Flash/useFlash.js
- src/Flash/withFlash.jsx
- src/index.js
- stories/Flash.stories.jsx
- yarn.lock
For https://github.com/user-interviews/ui-design-system/issues/24
Move flash message component into design system and include hook (and pass through HOC that uses the hook too) for better reusability in app components.
> UIDS-24 Flash message components

- .eslintrc
- .storybook/webpack.config.js
- src/RadioButton/RadioButton.jsx
- src/RadioButton/RadioButton.scss
- stories/RadioButton.stories.jsx
- Adds labels
- Adds children
- Adds styles
> [FEAT] Add new props to radio button

- src/Select/AsyncSelect.jsx
- src/Select/SingleSelect.jsx
Another pass-through prop that I missed the first time to set a defaultValue on the AsyncSelect.
> CHORE Add defaultValue to AsyncSelect

- .eslintrc
- spec/Select/AsyncSelect.test.jsx
- spec/Select/SingleSelect.test.jsx
- spec/__snapshots__/Storyshots.test.js.snap
- src/FormGroup/FormGroup.scss
- src/Select/AsyncSelect.jsx
- src/Select/SingleSelect.jsx
- src/Select/index.js
- src/Select/styles.js
- src/index.js
Fixes #48 
We noticed when trying to switch to the design system components in the project filtering task that the heights did not quite match up between the design system and the form controls in rails-server.  This was due to a piece of css overriding the height of .form-control in rails-server, but which did not apply to the DS selects.  See there is a small 1px difference:
From the discussion in the design system slack, it sounds like the height in rails-server (```height: 2.25rem;```) is the correct one.  So here I attempt to make the default design system styles reflect this.  I added a size prop to the selects like we did for modals because I imagine there will be cases where we could want a larger select.  I didn't include any other sizes yet though b/c wasn't sure what we would …
> UIDS-48 Make select heights consistent with other input controls

- src/InputLabel/InputLabel.scss
> CHORE update Input helper text color to be accessible

- src/CheckboxButton/CheckboxButton.jsx
- src/FormControlLabel/FormControlLabel.jsx
- src/Input/Input.jsx
- src/RadioButton/RadioButton.jsx
- src/RadioButtonGroup/RadioButtonGroup.scss
Added forwardRef for use with React Hook Form and a few styling tweaks:
- Radio buttons that are part of a RadioButtonGroup should have bold text
- Added row orientation to RadioButtonGroup
- Additional padding b/t buttons in RadioButtonGroup
Unclear if we may need more tweaks after the first radio goes through review but I think these are the most obvious ones. I paused the refactoring of RadioButton for now due to time constraints as it wasn't blocking yet.
> CHORE Add forwardRef to RadioButton and some styling tweaks

- spec/__snapshots__/Storyshots.test.js.snap
- src/RadioButton/RadioButton.scss
Small tweak to the RadioButton row layout to stretch the full width of the container:
> CHORE Update radio button row layout to stretch full width

- scss/forms/form_control_label.scss
- src/CheckboxButtonGroup/CheckboxButtonGroup.scss
- src/FormControlLabel/FormControlLabel.jsx
- src/RadioButton/RadioButton.scss
- src/RadioButtonGroup/RadioButtonGroup.scss
- stories/Form Elements/FormControlLabel.stories.jsx
- stories/Form Elements/RadioButton.stories.jsx
This doesn't completely finish this issue b/c we still have the refactor of `RadioButton` component, but I am not touching that for now b/c it will require a decent amount of changes in the app. But this branch enables `FormControlLabel` to accept children, so we can use that for helper text associated with checkboxes, like the Double screening checkbox:
Bordered checkbox not in a CheckboxButtonGroup
- Grey border
- No blue active state
- More padding (1rem)
- Children are ux-gray-800 and font-type-30 and fill the width
Bordered checkbox in a CheckboxButtonGroup
- Grey border
- Active state is highlighted blue
- Padding is tighter
> UIDS-87 Part one: allow FormControlLabel to accept children

- scss/forms/form_control_label.scss
- src/FormControlLabel/FormControlLabel.jsx
- src/Popper/Popper.scss
- src/RadioButtonGroup/RadioButtonGroup.scss
- src/Tooltip/Tooltip.scss
- stories/Form Elements/FormControlLabel.stories.jsx
Design feedback from https://github.com/user-interviews/rails-server/pull/5218
[ ] Fix checkbox shrinking on mobile
[ ] Give Tooltip messages font-weight 400
[ ] Vertically center tooltip icon
[ ] Fullwidth Radio buttons have extra right margin on mobile when they wrap to vertical column
> CHORE Update to disabled radio styles, tooltip font weight

- spec/__snapshots__/Storyshots.test.js.snap
- src/CopyToClipboardButton/CopyToClipboardButton.jsx
- src/Form/Form.jsx
Closes #121 
Reproduces the existing behavior of the common/form component, which accepts an action prop and can support an html form POST in addition to an ajax call. The code is mostly taken from the rails-server component except that it can accept a CSRFToken and CSRFParam.
> UIDS-121 Add support for html form post to Form component

- scss/forms/form_group.scss
- scss/forms/input_label.scss
- spec/Flash/__snapshots__/withFlash.test.jsx.snap
- spec/__snapshots__/Storyshots.test.js.snap
Fixes a few styling changes requested on radio buttons and checkboxes:
- Changes font-size to 30 for labels
- Makes label helper text wrap to a new line on mobile
> CHORE Update label font size for radio and checkbox, ensure wrapping on mobile

- README.md
Closes #137 
A start on some documentation for pull requests and merging. Much of this we already had in the rails-server README but also applies here. Trying to keep the process pretty light while a lot of things are still in development vs. when we eventually get more stable with less frequent updates.
> UIDS-137 Add merge process description to README

- .github/workflows/gh-pages-deploy.yml
- scss/forms/control_button_group.scss
- scss/forms/form_control_label.scss
- spec/__snapshots__/Storyshots.test.js.snap
- src/Select/styles.js
- src/Styles/fontWeights.js
Closes #149 
See temporarily deployed here: https://docs.userinterviews.com/ui-design-system/?path=/story/design-system-selects-async--default
[ ] FormControlLabel (e.g. Zoom or Other location link labels) should be bolded when it has additional helper text and is not within the context of a ControlButtonGroup ([see design system Figma specs](https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/Components?node-id=2145%3A396))
[ ] Update Select and AsyncSelect color to ux-gray-900 and font-weight: 300 when it is filled. (arrow icon should also always be ux-gray-600)
[ ] Align radio button icons to the top of each option on mobile (e.g. Incentive distribution)
Radios & Checkbox options with and without bolding:
Select font color and weight:
> UIDS-149 Some css updates from the project builder design review

- .github/workflows/release.yml
Closes #244 
There might be a better way to do this, I sort of put this together by following various tutorials I could find for the different pieces. The goal here is to automate the release process for the design system to make it easier/more streamlined and enable us to have more frequent releases. The workflow is as follows:
- This is a manually triggered github action, so it only runs when you manually request it. However, I haven't tested that part yet as the workflow_dispatch trigger is only supported on the main branch. So in testing I was triggering it on push, but may need a followup branch if there is any issue with the workflow_dispatch trigger once it is merged to main.
- Checkout the code, install the yarn dependencies, etc
- Auto increments the package version by either …
> Feature/UI ds 244 release GitHub action

- spec/__snapshots__/Storyshots.test.js.snap
- src/CheckboxButton/CheckboxButton.jsx
Since we are setting the indeterminate state via JavaScript now, we can remove the indeterminate attribute from the `input` element which helps us avoid that boolean value console error.
> removes indeterminate attribute from CheckboxButton input element

- src/Alert/Alert.scss
Hey team -- I noticed that the CTA is centered in alerts vs right aligned. I'm not sure how much went into this decision (so if it was a lot please ignore me) but to my eye this looks better:
Before: 
After:
Note -- this doesn't touch the sub 450px version (where it's left aligned under the initial text).
> Move alert CTAs to the end of the alert vs. centered

- src/Select/AsyncSelect.jsx
- src/Select/SingleSelect.jsx
This is necessary for adding an ID to the input element in React Select for use with `for` on forms.
I had the idea of changing the `id` to point here but that would block the ability to set ID on the react-select element which may cause other issues.
> UIDS-354 Add inputId to react select components.

- spec/__snapshots__/Storyshots.test.js.snap
- src/Select/AsyncSelect.test.jsx
- src/Select/SingleSelect.jsx
- src/Select/SingleSelect.stories.jsx
- src/Select/SingleSelect.test.jsx
- src/Select/styles.js
- src/Styles/colors/inputs.js
Closes #337 
We override some styles from the design system select components in the app. This PR moves these styles to be the default from the design system. Namely:
- Supporting the multi-select
- Updating the default selected color to blue for the mult-select
- Setting height to auto vs. a fixed height to support line-wrapping on the multi-select dropdown
- Making selected border blue with drop shadow to match app styles
- Set remove button styles from multi-select to match app styles
> Feature/UIDS-337 update multiselect styles to match rails-server

- spec/__snapshots__/Storyshots.test.js.snap
- src/Alert/Alert.jsx
- src/Toast/__snapshots__/withToast.test.jsx.snap
In the situation where we have more than one Alert being displayed, we have multiple buttons with the ARIA label of 'close' which makes it hard to differentiate between the two. This PR will add the type of alert to the label, so the screen reader should read "close error" or "close announcement".
This also makes it easier to target the close button in testing library!
> Feature/UI ds 453 improve close button aria labels on Alert

- spec/__snapshots__/Storyshots.test.js.snap
- src/Card/Card.jsx
closes #470 
- This should make the `Card` component less opinionated on layout. Ran into this issue before where I was trying to create a flexbox layout, but because the `Card__header` always rendered, it made it difficult to do things like justify-content. Example [here](https://github.com/user-interviews/rails-server/pull/8593#discussion_r746930193)
Note to self: will need to QA on rails-server since there may be places where we were writing custom css to get around this issue.
> hotfix/UIDS-470 update Card to conditionally render header

- jest.config.js
- package.json
- spec/__snapshots__/Storyshots.test.js.snap
- spec/spec_helper.js
- spec_helper.js
- src/Tabs/Tab/Tab.jsx
- src/Tabs/Tab/index.js
- src/Tabs/Tabs.jsx
- src/Tabs/Tabs.mdx
- src/Tabs/Tabs.stories.jsx
- src/Tabs/Tabs.styles.js
- src/Tabs/Tabs.test.jsx
- src/Tabs/__snapshots__/Tabs.test.jsx.snap
- src/Tabs/index.js
- src/index.js
- yarn.lock
Added `react-bootstrap` so we can wrap their `Tabs` and `Tab` components and then added `styled-components` so the style overrides don't get loose in `rails-server`.
Added a bunch of `react-testing-library` packages and added a spec helper so that `jest-dom` functions such as `toHaveClass` and `toBeInTheDocument` accessible in tests without having to import in every file.
Screenshot showing new design system tabs (top) and current rails tabs (bottom) look and act the same. Will be separate pr to implement in rails-server once `Tabs` are live.
Didn't add theming since felt like would be a lot for one pr but I would love to, so maybe will add? Otherwise used variables instead for shared css values which might not be the most graceful solution?
Screenshots from storybook:
Known issues small …
> Feature RS-8352 Tabs

- spec/__snapshots__/Storyshots.test.js.snap
- src/Select/AsyncCreatableSelect.jsx
- src/Select/AsyncCreatableSelect.stories.jsx
- src/Select/index.js
- src/index.js
CLoses #438 
Right now we make use of two different versions of react-select on rails-server and uids. This PR sets up some missing functionality to remove from rails-server and only use the DS component.
> UIDS-438 Add AsyncCreatableSelect

- src/Form/Form.jsx
- src/Form/Form.mdx
Previously passing a GET method would have worked for Rails, but it wouldn't
put the params in the URL which is the expected behavior. This makes it so we
properly pass GET directly to the form method parameter.
One other thing this does is remove the CSRF params if GET is passed. These are
ignored in GET and thus aren't necessary and would add extra params to the URL.
One potential upgrade that was left on the cutting room floor was passing any
extra props directly to the form component.
> UIDS-506 Update Form to handle GET method

- .github/workflows/gh-pages-deploy.yml
Fix deploy script to use correct node version
I think this might actually be the real issue with the ally plugin not working on the deployed storybook page
> CHORE Fix node version in deploy action

- cypress/integration/alert_spec.js
- cypress/integration/avatar_spec.js
- cypress/integration/button_spec.js
- cypress/integration/card_spec.js
- cypress/integration/checkbox_button_spec.js
- cypress/integration/copy_to_clipboard_button_spec.js
- cypress/integration/copy_to_clipboard_spec.js
- cypress/integration/dropdown_spec.js
- cypress/integration/form_elements/checkbox_button_group_spec.js
- cypress/integration/form_elements/form_control_label_spec.js
- cypress/integration/form_elements/form_group_spec.js
- cypress/integration/form_elements/radio_button_group_spec.js
- cypress/integration/form_spec.js
- cypress/integration/icon_cell_spec.js
- cypress/integration/loading_overlay_spec.js
- cypress/integration/modal_spec.js
- cypress/integration/pill_spec.js
- cypress/integration/popper_spec.js
- cypress/integration/profile_cell_spec.js
- cypress/integration/radio_button_spec.js
- cypress/integration/selects/async_spec.js
- cypress/integration/selects/creatable_spec.js
- cypress/integration/selects/single_spec.js
- cypress/integration/table_spec.js
- cypress/integration/toast_spec.js
- cypress/integration/tooltip_spec.js
- cypress/support/commands.js
Resolves #521 
Most recent build on branch:
https://percy.io/f38ae9b9/ui-design-system/builds/15127872
This looks like it fixes the flappy visual tests we have seen due to the accessibility tests running after the component has rendered in the iframe. We also got rid of all the `wait`s since we are asserting on the `Tests completed` text instead which seems to be working better. We also needed to check on the navigation element on the left of the page being rendered as well.
> bug/UIDS-521 wait for accessibility tests (and navigation) before Percy snapshot

- spec/__snapshots__/Storyshots.test.js.snap
- src/CardList/CardList.jsx
- src/CardList/CardList.mdx
- src/CardList/CardList.scss
- src/CardList/CardList.stories.jsx
- src/CardList/index.js
- src/index.js
closes #566 
Note: Comment out `margin: $card-spacing auto;` in `src/Card/Card.scss` before viewing.
We're opting to create a layout component `CardList` as an alternative to bringing in `Grid` from MUI. This should be simpler and solve for what we're wanting the accomplish: eventually removing `margin` and centering responsibilities from `Card` . 
This should hopefully handle most cases where we use the DS `Card` as they're just stacked on top of each other and centered. 
What it would look like on RS:
> add CardList to DS

- cypress/integration/pill_spec.js
- spec/__snapshots__/Storyshots.test.js.snap
- src/Pill/Pill.jsx
- src/Pill/Pill.mdx
- src/Pill/Pill.scss
- src/Pill/Pill.stories.jsx
- src/Pill/Pills.jsx
- src/Pill/Pills.scss
- src/Pill/index.js
- src/index.js
closes #561 
https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/Components?node-id=2000%3A1155
- Removes Pill border and updates colors
- Change bg color on closeable Pills
- add white-space: nowrap to Pill
- add Pills layout container
> update Pill color and border

- src/Card/Card.scss
closes #549 
This removes centering responsibility off of `Card`. Responsibility falls under (soon to be renamed) `CardContainer`
> remove margin from Card

- cypress/integration/button_spec.js
- scss/buttons.scss
- scss/colors/palette.scss
- spec/__snapshots__/Storyshots.test.js.snap
- src/Button/Button.mdx
- src/Button/Button.scss
- src/Button/Buttons.stories.jsx
closes #592 
While working on transitioning the TrackedButton to use the DS Button, I found the need for adding variants for the different brands that we use primarily for authentication. One example is the `OauthButton`. 
Lmk if we have any others that we might be missing!
> add brand variants to Button

- src/index.js
closes #599 
Removing `TrackedButton` from DS exports. It's still used in `CopyToClipboardButton` but have some questions about its use in there (might need to rework it a bit). But for now, will just make sure we are only using `TrackedButton` from `common/analytics` on rails-server.
> removing TrackedButton from export

- spec/__snapshots__/Storyshots.test.js.snap
- src/Toast/Toast.jsx
closes #604 
Adds `aria-live="polite"` to the container that holds the `Toast` which will be read aloud to a screen reader in a non-disruptive way. We received feedback for the P messenger that at least having a screen reader say "Message sent" instead of the entire message list would be better. 
https://user-images.githubusercontent.com/37383785/166520070-863cb1d8-5c48-432f-8478-7201caadb03d.mov
> add aria-live to Toast

- spec/__snapshots__/Storyshots.test.js.snap
- src/Alert/Alert.jsx
- src/Toast/Toast.stories.jsx
- src/Toast/__snapshots__/withToast.test.jsx.snap
- src/Toast/useToast.js
closes #606 
We previously weren't able to explicitly set the `title` prop for a `Toast` and often devs were finding it difficult to get this set properly (and sometimes were diverging from our defined styles). Hopefully adding this will make it easier. 
Something as simple as creating this:
Also, changed the `<p>` tags into `<div>` on the `Alert` component which should fix some of the issues explained here: https://userinterviews.slack.com/archives/CJYUKSM5M/p1650942546277709
Also just noticing now this margin override was made in `app/javascript/researcher/email_themes/builder/builder.jsx` and would have to be removed since the Alert message would change from a `<p>` to a `<div>`.
```
<Alert
message={(
<div style={{marginTop: '-1rem'}}>
Please note that this preview is approximate.
Make …
```
> handle setting title prop on Toast

- src/Select/styles.js
closes #614 
I think some parts of the custom `styles.js` for `option` was breaking the ability to tab through options and focus on them on our Select components. You should be able to tab through and the screen reader should be able to read through them all.
https://user-images.githubusercontent.com/37383785/168151426-e4cbffef-4f42-4519-a584-31c6c828bcb4.mov
> fix styles on Select to allow for tabbing and proper focus

- src/InputLabel/InputLabel.jsx
closes #620 
I was running into an issue with setting an `id` on an InputLabel and realized that wasn't possible since we didn't spread props on the component.
Mostly doing this in rare cases where you're using `InputLabel` by itself and some input element and need to set the `id` on it if another element is using `aria-labelledby` and needs it.
For context, working on `PhoneNumber` component which attempts to set id on `InputLabel` and causes some sad a11y error. Tested adding `id` in screenshot below for CountryCode to confirm. Sorry it's a bit hard to read.
> allow setting id on InputLabel

- cypress/integration/button_spec.js
- scss/buttons.scss
- spec/__snapshots__/Storyshots.test.js.snap
- src/Button/Button.mdx
- src/Button/Button.scss
- src/Button/Buttons.stories.jsx
closes #653 
Added a "Link" variant to the Button component. For cases where you need a `button` but just needed it styled like a link. Similar to adding a className of `btn-link` to a `<button>` on rails-server
By default:
- no underline
- underline appears only on hover
- `color: $ux-blue`
- hover color: `color: $ux-blue-600`
- disabled state: `opacity: 0.5`
https://user-images.githubusercontent.com/37383785/177643505-416cb658-1397-462f-857d-c2e743c2fdad.mov
`
> add Link variant to Button component

- package.json
- spec/__snapshots__/Storyshots.test.js.snap
- yarn.lock
closes #657 
Some reasoning behind wanting to upgrade to `react-select v5`:
- We were using version 3 which dates back to Oct 2019 and it seems like there have been noticeable improvement since then.
- Accessibility: some noticeable a11y improvements were introduced in v5 which honestly relieves some of the gripes we've had about a11y in react-select (also fixes some issues that Atlassian has pointed out).
v5 Release notes: https://github.com/JedWatson/react-select/releases/tag/react-select%405.0.0
Specific patch included in this version that helps with screen reader accessibility: https://github.com/JedWatson/react-select/issues/4695
We need the `Select` `placeholder` to be read aloud by the screen reader. The `v5` update includes a change that adds the role of `combobox` and the …
> upgrade react-select v5

- spec/__snapshots__/Storyshots.test.js.snap
- src/Accordion/Accordion.mdx
- src/Accordion/Accordion.stories.jsx
- src/Accordion/AccordionCollapse.scss
- src/Accordion/AccordionItem.jsx
- src/Accordion/AccordionItem.scss
- src/Accordion/AccordionToggle.scss
closes #670 
Some updates to the Accordion
- added story for wrapping Accordion in Card
- update borderless prop
*some weirdness with bootstrap overrides with `flush` prop when used on rails-server. Added `borderless` to handle our use case and works fine on `rails-server`. Just using `flush` here to showcase correctly on Storybook.
Build 23
https://www.chromatic.com/build?appId=62d040e741710e4f085e0647&number=23
> updates to Accordion v2

- src/FormGroup/FormGroup.jsx
Closes #695 
It turns out there's a situation where we need type node in the `labelTooltip` prop. See warning in builder. I didn't add it :(
> [UIDS-695] Make labelTooltip prop type node

- src/Select/styles.js
closes #683 
Just getting to this! Select option text color should now be using `$ux-gray-900`
> change Select option color to $ux-gray-900

- src/Dropdown/DropdownItem.scss
closes #705 
💅 when used on RS, the DropdownItem hover state gets overridden by `body.scss` which underlines all `a` tags on hover so just doing this here.
> text-decoration none on DropdownItem hover

- spec/__snapshots__/Storyshots.test.js.snap
- src/Dropdown/Dropdown.mdx
- src/Dropdown/Dropdown.stories.jsx
- src/Dropdown/DropdownItem.scss
- src/Dropdown/DropdownToggle.jsx
- src/Dropdown/DropdownToggle.scss
closes #694 
Chromatic: https://62d040e741710e4f085e0647-yqibtaubkj.chromatic.com/?path=/story/components-dropdown--custom-toggle
This is basically a styling escape hatch that TE will be using for the team selector dropdown. Example implementation on RS below:
https://user-images.githubusercontent.com/37383785/184400371-4061fbbe-f4b3-4f68-af3c-027cc4be53ab.mov
What is seen is all custom and can be written in `.scss` to make it like this. Some considerations:
- At current, we’d need to define the width to be exactly the same as what the nav width is if you want it to be centered. Otherwise, the API for the DropdownMenu (which uses popper.js as the library) will ask you … “do you want the menu to align with the start at the end of the toggle?”
- Devs would probably need to account for …
> add custom variant to DropdownToggle

- spec/__snapshots__/Storyshots.test.js.snap
- src/Pill/Pill.jsx
This fixes cypress-axe tests in RS that are failing when looking at pills.
> Add label for Pill close button

- src/Accordion/Accordion.jsx
- src/Accordion/AccordionItem.jsx
- src/Accordion/AccordionToggle.jsx
- src/ToggleInput/ToggleInput.jsx
closes #723 
Also exposes additional props instead of prop spread.
As much as I like the flexibility, it seems like prop spread should be used sparingly according to the [React docs](https://reactjs.org/docs/jsx-in-depth.html#spread-attributes). 
`"Spread attributes can be useful but they also make it easy to pass unnecessary props to components that don’t care about them or to pass invalid HTML attributes to the DOM. We recommend using this syntax sparingly." `
> remove prop spread on Accordion and ToggleInput

- spec/__snapshots__/Storyshots.test.js.snap
- src/Select/Option.jsx
- src/Select/SingleSelect.mdx
- src/Select/SingleSelect.stories.jsx
closes #726 
You should be able to set an `indeterminate` state on the `CheckboxButton` that is used in the custom `Option` component. 
Context exploration for an upcoming effort on Hub pod (this effort hasn't started yet, just fyi):
> update Option to allow for indeterminate CheckboxButton

- scss/forms/form_control_label.scss
- spec/__snapshots__/Storyshots.test.js.snap
- src/CheckboxButtonGroup/CheckboxButtonGroup.jsx
- src/CheckboxButtonGroup/CheckboxButtonGroup.mdx
- src/CheckboxButtonGroup/CheckboxButtonGroup.scss
- src/CheckboxButtonGroup/CheckboxButtonGroup.stories.jsx
- src/RadioButtonGroup/RadioButtonGroup.jsx
- src/RadioButtonGroup/RadioButtonGroup.mdx
- src/RadioButtonGroup/RadioButtonGroup.scss
- src/RadioButtonGroup/RadioButtonGroup.stories.jsx
closes #730 
**Chromatic Storybook links:**
[CheckboxButtonGroup - Bordered Column Full Width](https://62d040e741710e4f085e0647-voixuxvztu.chromatic.com/?path=/story/components-form-elements-checkboxbuttongroup--bordered-column-full-width)
[RadioButtonGroup - Bordered Column Full Width](https://62d040e741710e4f085e0647-voixuxvztu.chromatic.com/?path=/story/components-form-elements-radiobuttongroup--bordered-column-full-width)
We're making some updates for a better form experience for P's when taking Surveys, especially on mobile (for better touch targets)
- Updates the hover and active state of `FormControlLabel`
- Supports fullWidth for column orientations of `CheckboxButtonGroup` and `RadioButtonGroup`
- Updates stories and docs
Should eventually look something like this (new hover / …
> CheckboxButtonGroup and RadioButtonGroup state and width updates 

- spec/__snapshots__/Storyshots.test.js.snap
- src/Select/AsyncCreatableSelect.jsx
- src/Select/AsyncCreatableSelect.stories.jsx
- src/Select/AsyncSelect.jsx
- src/Select/AsyncSelect.stories.jsx
- src/Select/CreatableSelect.jsx
- src/Select/CreatableSelect.stories.jsx
- src/Select/SingleSelect.stories.jsx
- src/Tabs/__snapshots__/Tabs.test.jsx.snap
closes #742 
Our `modal` prop wasn't working with all of our Selects. It works for our `SingleSelect` which we fixed a while ago when we noticed that the ternary order in the `styles` prop was backwards, so just fixing it with all the other selects we have. Should be like this: 
```
styles={{
...defaultStyles({ size }),
menuPortal: (base) => (
modal ?
{ ...base, zIndex: zStack.zIndexModalBackdrop + 1 } :
base
),
}}
```
https://user-images.githubusercontent.com/37383785/190243609-69fe3eba-2d0e-49f2-9a23-f425767e69a2.mov
> make modal prop work with all Selects

- scss/variables.scss
- spec/__snapshots__/Storyshots.test.js.snap
closes #738
Green and navy both have 500 values that are darker than they should be currently. This is because the non-numbered variables were used but those don't always correspond to the 500 value. I set them all to the 500 variables for consistency.
> Fix color system JS variable order

- spec/__snapshots__/Storyshots.test.js.snap
- src/FormGroup/FormGroup.stories.jsx
- src/Input/Input.jsx
Adds an `aria-label` to this button:
> Add aria-label for trailingIconOnClickSubmit Input

- spec/__snapshots__/Storyshots.test.js.snap
- src/Card/Card.jsx
- src/Card/Card.scss
- src/Container/Col.jsx
- src/Container/Container.jsx
- src/Container/Container.mdx
- src/Container/Container.stories.jsx
- src/Container/Row.jsx
- src/Container/index.js
- src/index.js
closes #749 
This PR brings in the Grid layout components from React Bootstrap. A few devs have asked for some basic layout components and thought it would be valuable to have. Hopefully it should be intuitive enough to align and manage basic content across all breakpoints, especially as we try to create better experiences on mobile screens.
Chromatic build: https://62d040e741710e4f085e0647-bcwpacclug.chromatic.com/?path=/story/layouts-container--default
(ask me for the join link if you don't already have access to Chromatic)
> add Grid components (Container, Row, Col)

- spec/__snapshots__/Storyshots.test.js.snap
- src/Card/Card.mdx
- src/Card/Card.scss
- src/Card/Card.stories.jsx
closes #755 
I think it needs to be `max-width: 100%` instead of `width: 100%` now that `Card` takes up the entire width, but we don't want it to overflow its parent container on mobile. Examples below:
> change width to max-width on Card

- spec/__snapshots__/Storyshots.test.js.snap
- src/InputLabel/InputLabel.jsx
- src/InputLegend/InputLegend.jsx
Removes the `-gray` css suffix from the tooltips in `<InputLabel/>` and `<InputLegend/>`
> Input label tooltip color

- spec/__snapshots__/Storyshots.test.js.snap
- src/Select/styles.js
closes #764 
Discussed in gardening. Gives more visual indication that the entire select is interactive, not just on the chevron. 
https://user-images.githubusercontent.com/37383785/194646459-aeba5043-6c7c-463c-b68a-9616c7c471f6.mov
> update cursor to pointer on select control

- src/Select/OptionWithDescription.jsx
- src/Select/SingleSelect.stories.jsx
closes #784 
Chromatic: https://62d040e741710e4f085e0647-yopxegfste.chromatic.com/?path=/story/components-selects-single--custom-option-with-description
- adds `labelDescription` in cases where the `label` needs additional context
- uses `hideDescription` in cases where you need to hide the description when viewing on mobile
> add labelDescription to OptionWithDescription

- spec/__snapshots__/Storyshots.test.js.snap
- src/CardStack/CardStack.stories.jsx
- src/Container/Container.mdx
- src/Flex/Flex.jsx
- src/Flex/Flex.mdx
- src/Flex/Flex.stories.jsx
- src/Flex/Flex.types.js
- src/Flex/FlexWrapper.styles.js
- src/Flex/index.js
- src/index.js
closes #780 
The `<Flex>` layout component makes use of `styled-components`. I thought it would make more sense to use this instead of the usual classnames convention since there are so many possible flex properties that you can use. This is probably only my second time using styled-components so let me know if there are some best practices or conventions I'm overlooking.
Also I added what I thought were the most commonly used flex properties, but let me know if you want another one added or changed! Play around with the Storybook knobs in the build below:
Chromatic build: https://62d040e741710e4f085e0647-ukafrrrmop.chromatic.com/?path=/story/layouts-flex--default
> add Flex component

- src/Table/TableCell.scss
closes #792 
Decrease <TableCell compact /> padding from 1rem to 0.75rem which we only use on `app/javascript/researcher/participant_search/filtered_view/private_participant_table.jsx` and `app/javascript/researcher/account_project_dashboard/admin_controls.jsx`. We believed that it would be better for displaying more data rows. (Will follow up with making the "View" button on Hub table the small variant as well).
[Chromatic link to see the diff](https://www.chromatic.com/test?appId=62d040e741710e4f085e0647&id=638fc3b0a91e893b12eade54)
> update TableCell compact variant to 0.75rem top padding

- spec/__snapshots__/Storyshots.test.js.snap
- src/Pill/Pill.jsx
- src/Pill/Pill.mdx
- src/Pill/Pill.scss
- src/Pill/Pill.stories.jsx
closes #789 
[Chromatic link](https://www.chromatic.com/build?appId=62d040e741710e4f085e0647&number=106)
- Adding a red Pill color
- Add Statuses story to give more meaning to the colors
*Future work: PD's are chatting about separating out `Pill` to handle statuses and create a generic `Label` or `Tag` to handle categorization. More to come on this!
> add red Pill color

- package.json
- src/LoadingSkeleton/LoadingSkeleton.jsx
- src/LoadingSkeleton/LoadingSkeleton.mdx
- src/LoadingSkeleton/LoadingSkeleton.stories.jsx
- src/LoadingSkeleton/index.js
- src/index.js
- yarn.lock
closes #798 
[Chromatic link](https://62d040e741710e4f085e0647-aautmrrylg.chromatic.com/?path=/docs/components-loadingskeleton--default#props)
- Add `react-loading-skeleton`
- Create guidelines on when to use `LoadingSkeleton` vs. `LoadingOverlay`
Future: possibly build `LoadingSkeleton` into existing components (e.g ProfileCell, Button, Table) to make it easier to automatically handle skeleton states during loading. Mostly wanting to make it as easy as possible to use LoadingSkeleton without having to [create many dedicated loading skeleton screens.](https://www.npmjs.com/package/react-loading-skeleton#:~:text=Don%27t%20make%20dedicated%20skeleton%20screens)
What it could look like: 
https://user-images.githubusercontent.com/37383785/208517987-2bbd7955-f6bf-420d-b546-0cc2831d1242.mov …
> add LoadingSkeleton

- spec/__snapshots__/Storyshots.test.js.snap
- src/LoadingSkeleton/LoadingSkeleton.jsx
- src/LoadingSkeleton/LoadingSkeleton.scss
closes #805 
There's a conflicting order webpack issue when used on RS that I'm thinking is due to `import 'react-loading-skeleton/dist/skeleton.css';`. I just copied that code and made a separate `LoadingSkeleton.scss` 
I ran into a similar issue with [ToggleInput](https://github.com/user-interviews/ui-design-system/blob/develop/src/ToggleInput/ToggleInput.scss#L81) a while back where I did the same thing to resolve the issue. I'm hoping this will be the same fix 🤞
> import skeleton.css directly

- spec/__snapshots__/Storyshots.test.js.snap
- src/Tabs/Tabs.jsx
- src/Tabs/Tabs.styles.js
- src/Tabs/__snapshots__/Tabs.test.jsx.snap
Fix #809
Current state and without `flexWrapUnset` nor `navItemButtonFullHeight`
https://user-images.githubusercontent.com/54962889/212375185-2120164d-b375-4c07-8ffb-bc8fc8c96fbc.mov
With `flexWrapUnset` but without `navItemButtonFullHeight`
https://user-images.githubusercontent.com/54962889/212375298-69fc33ab-e0f7-4b4e-822e-57568e303494.mov
With `flexWrapUnset` and `navItemButtonFullHeight`
https://user-images.githubusercontent.com/54962889/212375375-16d6fa38-6dd0-475d-85ff-c463e6184752.mov
I think there's a case to be made that both of these css changes should be by default added to this component without those props, but it's up to @jasonbasuil to decide
> Adding optional props to Tabs component

- spec/__snapshots__/Storyshots.test.js.snap
- src/Card/Card.jsx
- src/Card/Card.mdx
- src/Card/Card.scss
- src/Card/Card.stories.jsx
- src/LoadingSkeleton/LoadingSkeleton.mdx
- src/LoadingSkeleton/LoadingSkeleton.stories.jsx
closes #820 
[Chromatic ](https://62d040e741710e4f085e0647-uiyinijedk.chromatic.com/?path=/story/components-card--loading)
Adding a pre-built, generic LoadingSkeleton directly into Card. This is easier for consumption with how we handle loading in most places.
Originally I had tried creating custom skeletons for some existing pages, but it ended up needing to make guesses on what `height` to give LoadingSkeleton in order to match what the Card would eventually render. It was also a little tedious to handle loading states with ternaries which I had to do. It looked something like:
🚫 
https://user-images.githubusercontent.com/37383785/215599136-60b48a06-e457-4c55-8c34-5eb5b35c3956.mov
Design agreed it doesn't look as good, so we're thinking the pre-built option is the way to go. It's a …
> add pre-built loading skeleton to Card

- src/Select/AsyncCreatableSelect.jsx
- src/Select/AsyncSelect.jsx
- src/Select/CreatableSelect.jsx
- src/Select/SingleSelect.jsx
closes #826 
I've noticed in a lot of places when using any of the Select components, even if it is wrapped in a `<FormGroup>` or has some `<label>` wrapped around it, if the `inputId` is not set, then screen readers can't associate the label to the select control (also you can't click the label to set focus on the Select). 
It will require a little bit of cleanup on RS but shouldn't be difficult to search for all the Selects and just add an `inputId`. Hopefully this encourages others to connect their Selects properly. You should get console warnings like this:
😢
https://user-images.githubusercontent.com/37383785/216440810-63005e01-cf13-4695-ae67-de2dc73b4460.mov
😃 
https://user-images.githubusercontent.com/37383785/216440503-b322d100-dcfe-4092-86fe-f473a6576fc7.mov
> make inputId required on Select components

- spec/__snapshots__/Storyshots.test.js.snap
- src/Button/Button.jsx
- src/Button/Button.mdx
- src/Button/Button.scss
- src/Button/Buttons.stories.jsx
closes #832 
[Designer input] ✅ 
Chromatic: https://62d040e741710e4f085e0647-ommuyhbzsq.chromatic.com/?path=/story/components-button--loading
- Loading state has spinner
- Loading state only available when paired with disabled state
- Able to customize `loadingText`
> add loading state to Button

- scss/buttons.scss
closes #837 
[Chromatic](https://62d040e741710e4f085e0647-hnbmefbaku.chromatic.com/?path=/story/components-button--primary)
Design reviewed ✅ 
We're reserving the blue focus outline on Button for keyboard navigation only. We'll eventually discuss removing the blue outline for other components (Accordion, Dropdown, etc.) next week.
> set Button focus outline to only keyboard

- spec/__snapshots__/Storyshots.test.js.snap
- src/Toast/Toast.jsx
- src/Toast/Toast.mdx
- src/Toast/Toast.stories.jsx
- src/Toast/useToast.js
- src/Toast/useToast.test.js
- src/Toast/withToast.test.jsx
Resolves #836 
Update `setMessage` in `useToast.jsx`  to expect an object with `message`, `title`, `action`, and `type` keys and become order agnostic.
Add Toast.mdx with Props table and `useToast` documentation:
> Update setMessage to accept object in useToast.js and add Toast.mdx doc file

- scss/avatars.scss
- scss/theme.scss
- spec/__snapshots__/Storyshots.test.js.snap
- src/Avatar/Avatar.scss
- src/ProfileCell/ProfileCell.jsx
- src/ProfileCell/ProfileCell.mdx
- src/ProfileCell/ProfileCell.stories.jsx
- src/ProfileCell/ProfileCellSkeleton.jsx
- src/ProfileCell/ProfileCellSkeleton.scss
- src/ProfileCell/index.js
- src/index.js
closes #824 
[Chromatic](https://62d040e741710e4f085e0647-ikucpqxlpj.chromatic.com/?path=/story/components-profile-cell--loading)
Creating another pre-built skeleton for ProfileCell. Also exporting `ProfileCellSkeleton` as a convenience if loading state management isn't as easy to implement on the ProfileCell itself which I had to do in the example below:
Testing out on Messages page in RS:
Before:
https://user-images.githubusercontent.com/37383785/216151084-b9d40f90-57ba-4e8a-8c48-2cd179142269.mov
After:
https://user-images.githubusercontent.com/37383785/216150152-97e64084-5b3a-4536-832f-f1f5de961878.mov
> add ProfileCellSkeleton

- spec/__snapshots__/Storyshots.test.js.snap
- src/Button/Button.jsx
- src/Button/Button.scss
- src/Button/Buttons.stories.jsx
- src/Button/index.js
- src/index.js
closes #848 
"Explore how proposed button sizes impact usability and aesthetics of buttons in product, and create a new proposal for new button sizes. "
- exposes `large` Button variant
- updates Button typography for each size (small = `font-type-30--medium`, medium = `font-type-40--medium`, large = `font-type-50--medium`)
- updates padding and thus changing heights (`28px`, `36px`, `44px`) 
[Chromatic](https://62d040e741710e4f085e0647-qdqgjeugex.chromatic.com/?path=/story/components-button--primary)
Related to product design initiative: [Button size testing (2/2)](https://www.notion.so/user-interviews/Button-Size-Testing-2-2-18dd05c26d814b05bdcb91adfe7692c8)
Design reviewed ✅ 
"Status as of 03.08 We’ve reviewed the buttons created by Jason in chromatic. Next steps are to have Jason …
> Button height updates

- src/Dropdown/DropdownItem.jsx
closes #889 
Pretty 💅 but realized not all icons are the same size and is important for [aligning fixed width](https://fontawesome.com/v4/examples/#:~:text=sufficient%20line%2Dheight.-,Fixed%20Width%20Icons,-View%20LESS%20View) all DropdownItems in a menu 
Before:
After:
> add fa-fw to DropdownItem

- scss/buttons.scss
- spec/__snapshots__/Storyshots.test.js.snap
- src/Button/Buttons.stories.jsx
closes #893
- Make `outline-transparent` disabled more obvious based on Veronica's design
- Add `disabled` Button examples in Storybook
> Improve outline transparent button disabled state

- spec/__snapshots__/Storyshots.test.js.snap
- stories/Spacing/Spacing.mdx
- stories/Spacing/Spacing.stories.jsx
closes #913 
Exposing our `$ux-spacing-xx` variables on Storybook. Mentioned from this PR as something that would be useful to surface: https://github.com/user-interviews/rails-server/pull/18054#discussion_r1176918363
> add Spacing stories to foundations

- src/Drawer/Drawer.scss
Closes #920
* The breakpoints weren't working as intended on tablet sized screens. Improved the media queries so when the screen size hits the width of the drawer the drawer becomes 100% width, for all size variants.
* Switched to standard media queries instead of Bootstrap's mixin since we don't use it elsewhere
https://github.com/user-interviews/ui-design-system/assets/20173797/71a24214-7a40-4572-92f6-3fb8819b9984
https://github.com/user-interviews/ui-design-system/assets/20173797/5222a46c-aa05-40e9-b7fd-aa06a820c453
> Improve Drawer breakpoints on tablets

- scss/buttons.scss
closes #912 
Just moving this mixin into our `buttons.scss` file. Related to PR: https://github.com/user-interviews/rails-server/pull/18123
> move btn-focus-outline--dark-bg to buttons styles

- package.json
closes #925 
Bumping the `node` version max to 19. We're aiming for `18.16.0` on RS, since 16 is EOL in September.
> bump node version max to 19

- package.json
- yarn.lock
closes #927 
Removing `react-scripts` from our devDependencies. I think it was just added accidentally during the SB7 upgrade. There was no mention of it in the SB7 migration notes.
Running `yarn why react-scripts` yields the following and doesn't mention other packages
```
yarn why v1.22.15
[1/4] 🤔  Why do we have the module "react-scripts"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "react-scripts@5.0.0"
info Has been hoisted to "react-scripts"
info This module exists because it's specified in "devDependencies".
info Disk size without dependencies: "23.23MB"
info Disk size with unique dependencies: "23.23MB"
info Disk size with transitive dependencies: "23.23MB"
info Number of shared dependencies: 465
```
Also …
> remove unused react-scripts

- .github/workflows/chromatic.yml
closes #943 
We have about a 5,000 snapshot limit on Chromatic every month and I find myself getting closer to the limit more often / I have to think about hitting the limit. 
Changing the deploy step on `main` makes a little more sense at this point since we really just need to inspect the visual diffs before a release anyways. Also just reduces the noise on the Chromatic dashboard with all the pushes to `develop`
> change Chromatic build deploy on main branch

- package.json
- spec/__snapshots__/Storyshots.test.js.snap
- src/MoneyInput/MoneyInput.jsx
- src/MoneyInput/MoneyInput.mdx
- src/MoneyInput/MoneyInput.scss
- src/MoneyInput/MoneyInput.stories.jsx
- src/MoneyInput/index.js
- src/index.js
- yarn.lock
closes #736 
Chatted with Nat on RX Workflow and decided that it would be helpful to bring in a MoneyInput component which aligns with their current efforts relating to incentive editing (as well as improving the overall validation experience for existing currency inputs)
Primary Reviewer: Gabe
Secondary Reviewer(s): Dom, Stephen, Nat
You can view a live build in Chromatic here: https://62d040e741710e4f085e0647-ppfritpjca.chromatic.com/?path=/docs/components-moneyinput--docs
One example test from RS in `app/javascript/researcher/project_workspace/details/compensation_fields/index.jsx`
Before:
https://github.com/user-interviews/ui-design-system/assets/37383785/8310a0e9-af02-4e05-9a6a-f185522f14ab
After:
https://github.com/user-interviews/ui-design-system/assets/37383785/c34426af-5bf9-49a5-8 …
> add MoneyInput component

- .storybook/main.js
- .storybook/preview.js
- package.json
- spec/__snapshots__/Storyshots.test.js.snap
- src/Button/Button.jsx
- src/Button/index.js
- src/IconButton/IconButton.jsx
- src/IconButton/IconButton.mdx
- src/IconButton/IconButton.stories.jsx
- src/index.js
- yarn.lock
closes #952 
Chromatic: https://62d040e741710e4f085e0647-rikhiwebhn.chromatic.com/?path=/docs/components-iconbutton--docs
The IconButton component is used for creating clickable buttons with icons, commonly found in app bars, toolbars, and toggleable actions.
We also are wanting to help encourage and enforce a set of pre-defined common actions that will be available with the `IconButton`. We're hoping that this will create a bit more consistency with which icons we use since devs are able to choose from the entire FontAwesome library and it might not always be apparent which icon weight to use.
> add IconButton

- spec/__snapshots__/Storyshots.test.js.snap
- src/Alert/Alert.jsx
- src/Alert/Alert.mdx
- src/Alert/Alert.scss
- src/Alert/Alert.stories.jsx
closes #962 
RX Scheduling is wanting to use a new feature Alert (internally we're calling it a Callout) for their MVP launch. We're also un-publishing the `Announcement` variant story in favor for the `Feature` variant (since the Announcement and Info variant are essentially the same color and pattern, we want to reduce the visual fatigue for having both). We only use the Announcement variant in two places and can possibly swap those out when this is released.
Chromatic: https://62d040e741710e4f085e0647-jcpkzkmxws.chromatic.com/?path=/docs/components-alert--docs#feature
Figma: https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/Component-Library?type=design&node-id=12552-18929&mode=design&t=ENoIba8smtwEtWbn-0
Primary: Kyle
Secondary: Devin, Wen
> add feature variant to Alert / Callout, unpublish announcement variant

- src/Alert/Alert.jsx
closes #973 
Needing the option to set the `target` attribute on the Alert `action` in order to open a new tab.
> add target to Alert action

- src/EmptyState/EmptyState.scss
closes #982 
Related to: https://github.com/user-interviews/rails-server/pull/19944#discussion_r1287648545
Adjusting the title and subtitle of the EmptyState component to have the same `margin-bottom: 16px`. We ran into the case where there wasn't a need for a subtitle in one of the empty states and the distance between the title and primary action was just slightly squished. 
Chromatic: https://62d040e741710e4f085e0647-uwvngvhwqs.chromatic.com/?path=/story/components-emptystate--primary-action
> ensure EmptyState title and subtitle have same margin-bottom

- src/Accordion/Accordion.mdx
- src/Accordion/Accordion.stories.jsx
- src/Accordion/AccordionToggle.jsx
- src/Accordion/AccordionToggle.scss
Closes #985 
Within the screener improvements project there are a few tweaks that would be great to have in `AccordionToggle`.
- Allow the chevron to not go from full up to full down, instead do a quarter turn from sideways to down
- Display collapsed text which only shows if the accordion is closed
Mega short loom of them in action: https://www.loom.com/share/5b159ce1c36749869f663a885005fc63
I achieved these changes with a small amount of code:
- Added `chevronLateral` prop which when present adds a class that is used to do a little rotation to the SVG icon, **note** it doesn't look great when on the right, more natural when to the left.
- Add `collapsedText` prop which only shows if present and when `isCollapsed` is true
Hopefully I can get away with these changes! I think they are nice …
> Adding lateral style icon and collapsed text

- bin/unlink-rs
Occasionally when running `yarn rs:unlink`, rails-server would then fail to compile.  Running `yarn --check-files` after unlinking should prevent this from happening moving forward.  Will need to monitor to confirm this is fully resolved.
> Adds necessary final step for unlinking rs

- src/Tabs/tabs.module.scss
Rails server includes bootstrap _after_ the DS, which means that bootstrap's own styles take precedence over our own that are built on top. By doubling up the class name selectors here, we ensure that our styles take precedence.
**This should be treated as an interim solution.** 
Ultimately, we should have the DS own bootstrap & react-bootstrap altogether, with rails server only consuming BS _through_ the DS.
**Active tab state getting overridden**
**flexWrapUnset getting overidden**
> Fix tabs styles in RS

- spec/__snapshots__/Storyshots.test.js.snap
- src/FormGroup/FormGroup.mdx
- src/FormGroup/FormGroup.stories.jsx
- src/Input/Input.jsx
- src/Input/Input.scss
Adds `trailingText` to `Input`
Figma: https://www.figma.com/file/wU1NfHuJchd9xLirqBREQN/Research-Set-up?type=design&node-id=3569-7744&mode=design&t=aB8GD4SuTxyA5Mbs-0
Chromatic: https://62d040e741710e4f085e0647-nsyrdovjii.chromatic.com/?path=/story/components-form-elements-form-group--with-trailing-text
If `<Input type='number'`, add spacing for chevrons
https://github.com/user-interviews/ui-design-system/assets/37383785/bf820320-14a2-469e-9309-4ba4d1f5fd7e
If not `type='number'`, no spacing adjustment
> add trailingText to Input component

- spec/__snapshots__/Storyshots.test.js.snap
- src/Drawer/Drawer.jsx
- src/Drawer/Drawer.mdx
- src/Drawer/Drawer.stories.jsx
This is a feature that us at rx-workflow wanted as the contents that we were putting in was too big for the non-expanded state (needed to put the Calendar component inside). With that we wanted the drawer to be able to be expanded by default while not allowing for the user to click on a expanded button.
Creates a new prop `defaultExpanded`, which I chose the naming based off react-select's `defaultMenuIsOpen` naming (open to changes tho), that will set the initial value of the expanded state
> Allow drawer to be expanded by default

- src/Card/Card.scss
closes #1070 
Adds border to `Card` under the `.Synthesized` class. This should only affect the `Card` component when `.Synthesized` class is applied to the `<body>` when `@is_new_navigation_enabled` is enabled.
Looks like this (removing the border already applied in `app/javascript/researcher/account_project_dashboard/account_project_dashboard.scss`):
When `@is_new_navigation_enabled` is off:
> add border to Card under Synthesized class

- scss/colors/synthesis-palette.scss
- scss/variables.scss
Adds Sass variables for the [new Synthesis colors from Figma](https://www.figma.com/file/dmmTbSjuPXqt9m82YaewXO/Synthesis-Design-System?type=design&node-id=0-1&mode=design&t=lkmh9m9vVaDMtER6-0)
Todo:
> Add Synthesis colors from Figma

- spec/__snapshots__/Storyshots.test.js.snap
- src/CheckboxButton/CheckboxButton.jsx
- src/CheckboxButton/CheckboxButton.module.scss
- src/CheckboxButtonGroup/__snapshots__/CheckboxButtonGroup.test.jsx.snap
- src/RadioButton/RadioButton.jsx
- src/RadioButton/RadioButton.module.scss
closes #1073 
Small interaction detail, but an important one! `RadioButton` and `CheckboxButton` should have a `cursor: pointer` on them. 
Whoopsie: https://www.notion.so/user-interviews/No-pointer-cursor-on-checkboxes-or-radios-564eb93215394e82829a73dbd2672226
Primary: Devin, Kyle
> add pointer to CheckboxButton and RadioButton

- spec/__snapshots__/Storyshots.test.js.snap
- src/MoneyInput/MoneyInput.jsx
- src/MoneyInput/MoneyInput.mdx
- src/MoneyInput/MoneyInput.scss
- src/MoneyInput/MoneyInput.stories.jsx
closes #1093 
Chromatic: https://62d040e741710e4f085e0647-kqxazlwklf.chromatic.com/?path=/story/components-moneyinput--step
- removes `box-shadow` from MoneyInput to match flat UI aesthetic
- exposes `step` and `prefix` props 
Primary: Dom
Secondary: Gabe
> remove box shadow from MoneyInput, add step and prefix props

- src/Dropdown/DropdownItem.jsx
- src/Dropdown/DropdownItem.module.scss
closes #1090 
- Update the `DropdownItem` hover state to synth hover color (also uses CSS modules to avoid bootstrap collision)
- removes danger variant (we only use in one place currently, but PD says we can get rid of it)
Before:
https://github.com/user-interviews/ui-design-system/assets/37383785/b009f61f-fa5e-48ff-90f7-4d753794ecec
After:
https://github.com/user-interviews/ui-design-system/assets/37383785/a98c28d4-9aff-4ab4-9694-1b20bffc7288
> update DropdownItem hover state, remove danger variant

- spec/__snapshots__/Storyshots.test.js.snap
- src/Heading/Heading.stories.tsx
- src/Heading/Heading.tsx
closes #1095 
Chromatic: https://62d040e741710e4f085e0647-xcmihmyrti.chromatic.com/?path=/story/components-heading--sizes
- Makes only `level` and `size` required on `Heading`
- Changes default level from `2` to `1`
- Assigns default `size` props to every Heading `level`
- If `size` or `weight` are assigned, they will overtake the defaults 
I think this should simplify the need to assign each one of these props on the `Heading` component every time. Given a required `level`, it should be able to default to the a more logical sizing based on level. A dev can always override the size or weight based on visual hierarchy needs, but hopefully this reduces the friction to using the `Heading` component. 
Primary: Kyle, Gabe
> give default sizes to levels, make weight and size optional

- scss/forms/form_control_label.scss
- scss/forms/form_group.scss
closes #1101 
We don't use `font-weight: 100` which may have been causing some weird behaviors on some people's browsers even though it should get bumped up to the nearest available 400 font weight.
> remove font-weight: 100

- src/RichTextEditor/TemplateVariable.scss
When the variable list is too long, it would overflow the window and the bottom items become inaccessible.  This just sets a reasonable max-height.  This is sort of a hot fix and the popup should be updated to calculate it's height based on its position, but for now this does the trick.
> adds max height to template variable popup

- src/Alert/Alert.jsx
closes #1114 
Chromatic: https://62d040e741710e4f085e0647-dgnqhmugfu.chromatic.com/?path=/story/components-toast--default
- Sets Success variant dismiss timing to 3 seconds. This should make sense for Success messages as they tend to be shorter in word length and require less time to read (e.g. "Message successfully sent", "Email template saved successfully." I read in a couple places that a success toast can vary between 2-5 seconds so we've probably been on the longer end. Nat thought 3 seconds was good length.
- Keeps all other Toast variants at 5 seconds by default as users may need a bit more time to read and comprehend these messages. 
We could probably refine more, but this seems to solve the issue Nat described in Workflow.
> update Toast dismiss timing

- src/Card/Card.jsx
Allowing prop `title` from `Card` component to be have `node` type
> Allow prop type node for Card title

- src/Dropdown/DropdownToggle.scss
Closes #1153
If you click on the `DropdownToggle` to open the `Dropdown` then the button is `active`, which our CSS styles to be a different color. If you click it again then it closes but has focus so it is still the `active` color. If you click away then it loses `focus` and goes back to the original color.
As [this goofy JSFiddle](https://jsfiddle.net/eo7fhaL6/) demonstrates that is the expected behavior for buttons when they are clicked twice since clicking it gives it focus. You generally don't notice this since something usually happens to takes focus away from the button when it is clicked (like a form submit) and button focus states aren't styled that often.
It feels really wonky for a dropdown toggle, however. So this PR changes the styles to what we expected, which is that if …
> Fix DropdownToggle focus

- src/Drawer/Drawer.jsx
- src/Drawer/Drawer.scss
- src/Drawer/Drawer.test.jsx
[//]: # (
Provide a brief description of the intent of this pull request.
Example: Allow users to search for a specific product by name.
)
Fix #1100 
Primary: @kyleshike / @jasonbasuil / @gabescarbrough 
secondary: @frankhock / @Dchyk 
cc: @PLUCS2  
[//]: # (
How did you test this manually? How can your reviewer test the workflow?
If this is a bug, how can you reproduce the bug?
)
Link DS locally and verify if the background for drawers with `hasBackgroundOverlay` (by default `true`) is not scrollable
When opening the drawer 
https://github.com/user-interviews/ui-design-system/assets/54962889/9d034da0-4a81-44ef-871b-fcf927642865
When going to the drawer via URL (can still scroll within drawer)
https://github.com/user-interviews/ui-design-system/assets/54962889/6e93d5f7-7fd4-4a32-83e6-c4d18 …
> Disable drawer background scrolling if drawer has background overlay

- src/Drawer/DrawerBody.jsx
Need to pass a ref to this component to not show google places autocomplete when scrolling; rough idea in this PR https://github.com/user-interviews/rails-server/pull/24206
> Add forwardRef to DrawerBody

- src/RichTextEditor/RichTextEditor.mdx
- src/RichTextEditor/RichTextEditor.stories.jsx
- src/RichTextEditor/RichTextEditor.tsx
Us at rx-fast want a way to programmatically set the content within the RichTextEditor. Specifically for the team email templates page, we have an action to reset the editor content to a default. This exposes a `setContent` function that uses `setContent` from the editor object returned by the `useEditor` hook. Nat and I thought it was best to not have this be an extension as the behavior for email templates are pretty specific and so a generic reset icon within the actions toolbar might be ambiguous. 
https://github.com/user-interviews/ui-design-system/assets/65802187/18a36d31-1d2c-4cf2-9bed-10d8a194ab38
> Update RichTextEditor to be a forwardRef and expose setContent through useImperativeHandle

- scss/buttons.scss
- src/Button/Button.mdx
- src/Button/Button.scss
- src/Button/Button.stories.tsx
- src/Button/Button.tsx
Closes [#1185](https://github.com/user-interviews/ui-design-system/issues/1185)
| Figma | Actual | Actual + focus |
|--------|--------|--------|
|  <img width="664" alt="Screenshot 2024-04-11 at 3 31 14 PM" src="https://github.com/user-interviews/ui-design-system/assets/16170530/2536b42e-161f-494d-ba5f-5ef524e32793"> | <img width="785" alt="Screenshot 2024-04-11 at 3 33 22 PM" src="https://github.com/user-interviews/ui-design-system/assets/16170530/0a26eddf-48bd-4cbb-80ca-d7ab7447ea7f"> | <img width="789" alt="Screenshot 2024-04-11 at 3 33 28 PM" src="https://github.com/user-interviews/ui-design-system/assets/16170530/8ca857e6-9628-494b-a470-dd5e2fe4e144"> | 
Is it crazy to have added tertiary without adding secondary? I don't have an immediate need for secondary which is why I didn't add …
> Add Tertiary Button variant

- package.json
- scss/colors/synthesis-palette.scss
- scss/css_properties.scss
- src/Tabs/tabs.module.scss
https://github.com/user-interviews/ui-design-system/assets/3161151/8b2b9627-918b-4d08-a496-932c4808156e
Previously, hovered tab items would have their text bolded. In some situations, this can be problematic as bolded text is larger than non-bolded text (all else being equal). This difference causes some rather unfortunate content shifting.
Now, we use a lighter color on inactive tab items, and indicate the hover state by using text black on hover.
> Improves hover state of tabs

- .github/dependabot.yml
Allows Dependabot to open up PRs with library version upgrades, using a "widen" strategy by default which should be most compatible
> Enable Dependabot Version Upgrades

- src/Drawer/Drawer.scss
Closes: https://linear.app/user-interviews/issue/RXS-647/tweak-full-screen-drawers-to-be-90percent
Figma: https://www.figma.com/design/BXDtUK7ggGlNcDl2mtpL7i/Ad-hoc?node-id=100-172&t=X6YBKxqG0SaepoxD-0
Small change to make the fully expanded Drawer only ever take up a max of 90% of the screen. This is in response to user and product feedback about not being able to see any of the main page nav or anything else when drawers are fully expanded. 
Some examples of expanded drawers from the workspace after this change: 
Videos:
https://github.com/user-interviews/ui-design-system/assets/25135946/7acd379e-99ec-4479-8d9e-29f49f8a4ef0
https://github.com/user-interviews/ui-design-system/assets/25135946/ea5c4ea7-e912-4f32-80c8-993e35f2d40b
> Change Drawer expanded width to 90%

- .github/workflows/prepare-release.yml
Yarn 4 changes how `yarn version` works.  Where it previously accepted a numeric value, now it accepts `major, minor, patch` etc and bumps the version in package.json
Our previous GH workflow assumed this numeric value from user input and used it throughout for creating a corresponding branch, etc.  This PR fixes that by using the newer `yarn version` options for the user input of the workflow, and uses a script to read that value from the package.json file anywhere else that it's needed
> Fix GH actions to work with Yarn 4

- src/Select/AsyncSelect.jsx
- src/Select/AsyncSelect.stories.jsx
- src/Select/Option.jsx
- src/Select/Option.scss
- src/Select/SingleSelect.jsx
- src/Select/SingleSelect.stories.jsx
closes #1224 
https://www.figma.com/design/7oRnbovk9fZ1lgxfcSjWl9/Q2-%E2%80%93-Participant-Targeting?node-id=1262-4885&t=6BlgLSzn8pBVa65s-0
- Creates a new component: `Async Searchable MultiSelect`.
-- Is searchable.
-- Dropdown custom options have checkboxes the their left.
-- Has the `clear all` functionality i.e. `X` at the end of the input after values are input.
-- When an option is selected after the search runs, add the selected tag to the field and clear the user’s search input, but keep the search results open until the user either: Clicks out of the field (results drop-down should disappear) or Begins typing a new search (moves back into Loading/results states). (KILEY WANTS THIS BUT THE PROPS I ADDED DON'T SEEM TO BE WORKING ON IT. )
- Creates a new component: …
> Add async searchable multiSelect and searchable multiSelect types

- src/RichTextEditor/RichTextEditor.tsx
More context here https://github.com/ueberdosis/tiptap/issues/154
Changing this to empty string if tiptap deems its content to be empty instead of saving `<p></p>` which could create some unexpected behavior when checking if string is empty 
primary: @kyleshike 
seconday: @gabescarbrough @jasonbasuil
> Set RichTextEditor value to empty string if editor is empty

- scss/forms/form_group.scss
- src/FormGroup/FormGroup.mdx
- src/FormGroup/FormGroup.stories.tsx
- src/FormGroup/FormGroup.tsx
add `noMargin` prop for `FormGroup`. Wasn't sure if `variant` made sense to use here or even `spacing="none"`. Open to suggestions 
Or maybe even make a `FormGroupContainer` that has spacing={ 1 | 2 | 3 etc.) and uses the `<FlexContainer>`
> noMargin prop for FormGroup

- src/Select/Option.jsx
- src/Select/Option.scss
- src/Select/SingleSelect.stories.jsx
This PR allows you to use a description that's passed through the `data` prop so you get something that looks like this:
Since the `Option` component and its accessible props seem dictated by React Select, it looked like `data` was the best place to access this. Let me know if that's wrong and if you think there's a better way to do this.
> Adds description to `Option`

- src/Select/Option.jsx
- src/Select/Option.scss
closes REC-16
Needed the alignment of the Option with checkbox and description to be top aligned
fIgma: https://www.figma.com/design/7oRnbovk9fZ1lgxfcSjWl9/Q2-%E2%80%93-Participant-Targeting?node-id=1985-24512&t=I3gIhs3EhmW3aYVm-0
Before:
After:
On RS:
> fix alignment of Option with checkbox and description

- src/Drawer/Drawer.test.tsx
- src/Drawer/Drawer.tsx
This is a common request that keeps coming in from users so this seems like a quick fix for now, until we can implement fully prompting before closing on drawers when anything has been changed (which is TBD [here](https://linear.app/user-interviews/issue/RXS-304/drawer-behavior) already) 
https://userinterviews.slack.com/archives/C5Y7A9A1M/p1724078969522259
https://linear.app/user-interviews/issue/RXS-1384/disable-survey-drawer-closing-on-background-clicks
Demo: 
https://github.com/user-attachments/assets/4e633245-2bd7-4771-b527-f090a5cf1dc1
> Add optional disabling of drawer close on background overlay click

- src/Accordion/Accordion.stories.tsx
- src/Accordion/AccordionCollapse.scss
- src/Accordion/AccordionToggle.scss
- src/Accordion/AccordionToggle.tsx
- src/Accordion/utils.ts
I noticed that adding the `alwaysOpen` prop to the Accordion caused the chevrons to stop rotating when the accordions were opened. This PR resolves that by allowing for arrays of `activeKeys` as well as single strings.
https://github.com/user-attachments/assets/34974478-7ff2-4b31-a1ba-1db4f4d73de1
> Add support for arrays of active event keys to Accordion

- .storybook/preview.js
- src/CardStack/CardStack.stories.tsx
- src/Container/Col.tsx
- src/Container/Container.mdx
- src/Container/Container.stories.tsx
- src/Container/Container.tsx
- src/Container/Row.tsx
- src/Flex/Flex.mdx
- src/Flex/Flex.stories.tsx
- src/Flex/Flex.tsx
- src/IconCell/IconCell.mdx
- src/IconCell/IconCell.stories.tsx
- src/IconCell/IconCell.tsx
- src/Main/Main.stories.tsx
- src/utils/index.ts
- src/utils/useDeprecationWarning.ts
closes ENG-226
- Adds `useDeprecationWarning` hook and adds them to the following components under a Deprecated storybook folder
- Deprecated components: `Flex`, `Container`, `Col`, `Row`, `IconCell`
- Moves the `Layout` component under `Components` just for ease of discovery amongst all components until / if we want to organize the folders another way.
- Updates story sort to ensure all components shown are now alphabetical in Storybook nav.
Should only warn in dev environments
No longer have that funky non-alphabetical sort that was happening with the remaining JSX files
> add deprecation warnings to components

- scss/buttons.scss
[//]: # (
See https://www.notion.so/Expectations-for-Code-Reviews-4c261233caf64f12ab459ba090be2c50 for more best practices around how we do Code Review.
This is a default pull request template that teams can use as a starting point.
You can edit this here: docs/pull_request_template.md
)
Closes [ENG-227](https://linear.app/user-interviews/issue/ENG-227/tertiary-button-updates)
[//]: # (
Provide a brief description of the intent of this pull request.
Example: Allow users to search for a specific product by name.
)
Update styling on tertiary button to match [new design](https://www.figma.com/design/dmmTbSjuPXqt9m82YaewXO/Synthesis-Design-System?node-id=1637-10978&node-type=canvas&t=0A1KSHA2k434BsvO-0).
[//]: # (
Indicate who your primary and secondary reviewers are, and make sure they know. …
> Tertiary button style updates

- src/ControlButtonGroup/ControlButtonGroup.tsx
Fixing console warning that prevented us from adding more frontend specs (since warnings make specs fail)
before
After
> ControlButtonGroup do not set bordered if child is a DOM element

- src/DateTimePicker/DateTimePicker.scss
- src/DateTimePicker/DateTimePicker.tsx
Without specifying `isWithinModal` or setting it to `false`
https://github.com/user-attachments/assets/78b43bfe-4d2b-4e8e-8689-5df24ca46482
With setting it to `true`
https://github.com/user-attachments/assets/e1f2fdda-a954-419e-9a76-e20310964046
it should behave in the same way as single select.
Took an inspiration from this recommended solution https://github.com/Hacker0x01/react-datepicker/issues/2545
> Add isWithinModal option to DateTimePicker

- src/CopyToClipboardButton/CopyToClipboardButton.tsx
Noticed this warning in rails server so removing here.
> Remove copy to clipboard button default props
