user-interviews/ui-design-system

.eslintrc, spec/__snapshots__/Storyshots.test.js.snap, src/Form/Form.scss, src/FormControlLabel/FormControlLabel.jsx, src/FormControlLabel/FormControlLabel.scss, src/FormGroup/FormGroup.jsx, src/InputLabel/InputLabel.jsx, src/InputLabel/InputLabel.scss, src/RadioButton/RadioButton.jsx, src/RadioButtonGroup/RadioButtonGroup.jsx, src/index.js, stories/Card.stories.jsx, stories/Form.stories.jsx, stories/FormControlLabel.stories.jsx, stories/FormGroup.stories.jsx, stories/Pill.stories.jsx, stories/RadioButton.stories.jsx, stories/decorators/index.js, stories/decorators/withPadding.jsx
Closes #20 
This takes some styling from the old "ui-form" CSS class and extracts it to the component level. Tested this on the opt-in page:
=> UIDS 20 Add RadioButton component

spec/__snapshots__/Storyshots.test.js.snap, src/FormGroup/FormGroup.jsx, src/FormGroup/FormGroup.scss, stories/FormGroup.stories.jsx
=> UIDS-22 add description prop to FormGroup

scss/palette.scss, scss/theme.scss, scss/z_stack.scss, src/Styles/palette.js, src/Styles/zStack.js
This brings over the z stack variables and introduces color variables to be used
for styled components as well as adding similar variables for z stack.
=> CHORE Add z_stack styles and JS add colors to JS

scss/palette.scss, src/Styles/index.js, src/Styles/palette.js, src/index.js, stories/Palette.stories.jsx
Also included exporting FadeTransition.
=> UIDS 29 Add all the colors and export them.

.github/workflows/gh-pages-deploy.yml
=> UIDS-15 deploy to github pages automatically after PRs are merged

.eslintrc, .github/workflows/gh-pages-deploy.yml, scss/baseline.scss, scss/global.scss, scss/typography.scss, spec/__snapshots__/Storyshots.test.js.snap, src/InputLabel/InputLabel.scss, stories/Alert.stories.jsx, stories/AsyncSelect.stories.jsx, stories/Flash.stories.jsx, stories/Form Elements/FormControlLabel.stories.jsx, stories/Form Elements/RadioButton.stories.jsx, stories/Popper.stories.jsx, stories/Styles/Typography/Typography.scss, stories/Styles/Typography/Typography.stories.jsx
Just a first start on the typography story and tokens. I expect we will iterate on this!
At first I had a token for every combination of size and weight, but I noticed other design systems being more opinionated about this. For example not giving the option to use a larger font with the highest font-weight, the smallest size for helper text does not have a bolded option, etc. I started that here but still trying to get a feel for what makes the most sense in our current usage in the app, we have a lot of combinations that we may be able to consolidate into fewer options once we do the designer review.
Story has been deployed here: https://docs.userinterviews.com/ui-design-system/?path=/story/design-system-styles--typography
=> UIDS-54 Initial commit of typography story

.github/workflows/gh-pages-deploy.yml
Got a bit too eager to merge 🤦
=> CHORE Reset github action to master

spec/__snapshots__/Storyshots.test.js.snap, src/Flash/AlertMessage.jsx, src/Flash/Flash.jsx, src/Flash/useFlash.js, src/Flash/withFlash.jsx, stories/Flash.stories.jsx, stories/Styles/Typography/Typography.stories.jsx
=> UIDS-59 Add optional autoDismiss prop to Flash component

.babelrc, package.json, scss/theme.scss, spec/__snapshots__/Storyshots.test.js.snap, src/CopyToClipboard/CopyToClipboard.jsx, src/Popper/Popper.jsx, src/Popper/Popper.scss, src/Tooltip/Tooltip.jsx, src/Tooltip/Tooltip.scss, src/Tooltip/index.js, stories/Popper.stories.jsx, stories/Tooltip.stories.jsx, yarn.lock
=> UIDS-61 Add Tooltip component

src/Popper/Popper.scss, src/Tooltip/Tooltip.jsx, stories/Tooltip.stories.jsx
closes https://github.com/user-interviews/ui-design-system/issues/63
result of https://github.com/user-interviews/rails-server/pull/4678/
=> UIDS-63 update tooltip text prop

src/Pill/Pill.jsx, src/Pill/Pill.scss, stories/Pill.stories.jsx
Also adds a 'squared' prop to make the pill have sharper corners.
=> [CHORE] Add green pill component

scss/inputs.scss, scss/theme.scss, spec/__snapshots__/Storyshots.test.js.snap, src/FormGroup/FormGroup.jsx, src/FormGroup/FormGroup.scss, src/Input/Input.jsx, src/Input/Input.scss, src/Input/index.js, src/InputLabel/InputLabel.jsx, src/InputLabel/InputLabel.scss, src/Pill/Pill.jsx, src/Tooltip/Tooltip.jsx, src/index.js, stories/Form Elements/FormGroup.stories.jsx, stories/Form.stories.jsx, stories/Pill.stories.jsx, stories/Tooltip.stories.jsx
Closes #70 
See in action [here](https://docs.userinterviews.com/ui-design-system/?path=/story/design-system-form-elements-form-group--default)
I tried to mimic all the varieties found in [this](https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/Components?node-id=1932%3A9) Figma
=> UIDS-70 Add Input component

src/FormGroup/FormGroup.jsx
=> UIDS-75 remove description prop from FormGroup

src/FormGroup/FormGroup.scss
=> UIDS-79 update Input error styling

scss/colors/palette.scss, src/Styles/colors/palette.js
=> UIDS-105-Update $ux-gray-900 to #101010

.github/workflows/gh-pages-deploy.yml, scss/forms/control_button_group.scss, spec/CheckboxButtonGroup/__snapshots__/CheckboxButtonGroup.test.jsx.snap, spec/__snapshots__/Storyshots.test.js.snap, src/CheckboxButtonGroup/CheckboxButtonGroup.jsx, src/CheckboxButtonGroup/CheckboxButtonGroup.scss, src/ControlButtonGroup/ControlButtonGroup.jsx, src/ControlButtonGroup/index.js, src/RadioButtonGroup/RadioButtonGroup.jsx, src/RadioButtonGroup/RadioButtonGroup.scss, stories/Form Elements/FormGroup.stories.jsx
Closes #116
Update row variant of RadioButtonGroup to better match design principles
=> UIDS-116 Add compact row styling of RadioButtonGroup

src/Pill/Pill.scss, stories/Pill.stories.jsx
We need to update the pills so they all have borders. 
The contrast of the current pills when used in gray backgrounds is very poor.
[Figma Variants](https://www.figma.com/file/471iS3QrpPtXZpS1xbsJ20/?node-id=1259%3A484)
=> [ Draft ] Update pills styling and add new variant

scss/colors/palette.scss
Adds google blue and yahoo brand colors
=> CHORE Add Google blue and yahoo brand colors

README.md
=> UIDS-144 Add release steps to README

.github/workflows/gh-pages-deploy.yml, package.json
Going to make a DS release. Also I messed up & merged the action even though you warned me about it 🤦
=> CHORE Upgrade design system package version

src/Toast/Toast.scss
=> fix: moves Toast to bottom right & fixes mobile issue

spec/Storyshots.test.js, spec/__mocks__/reactDomMock.js, spec/__snapshots__/Storyshots.test.js.snap, src/Popper/Popper.jsx, src/Popper/Popper.scss, src/Tooltip/Tooltip.jsx, src/Tooltip/Tooltip.scss, stories/Tooltip.stories.jsx
Added an arrow to the Tooltip component. Also changed the styling of the outline to be a little less obtrusive.
=> UIDS-211 Add arrow to Tooltip component

src/Popper/Popper.scss, stories/Tooltip.stories.jsx
https://github.com/user-interviews/ui-design-system/issues/219
Before:
After:
=> Change dark Popper link color

package.json
Update version number to match release
=> CHORE Update version number in package.json

.github/workflows/lint.yml, .github/workflows/test.yml
Closes #91 
Super simple actions to run tests and linter and report output on pull requests. Will send an email to the branch owner if the workflow fails.
=> UIDS-91 Enable github actions for linting and tests

scss/colors/palette.scss
=> chore/UIDS-270 Update 900 series colors for improved contrast (accessibility)

src/Alert/Alert.mdx, src/Avatar/Avatar.mdx, src/Card/Card.mdx, src/Form/Form.mdx, src/Modal/Modal.mdx, src/Pill/Pill.mdx, src/Popper/Popper.mdx, src/ProfileCell/ProfileCell.mdx
Super quick just fixes some imports that were throwing errors in console.
=> Some mdx files importing wrong component

scss/box_shadow.scss, spec/__snapshots__/Storyshots.test.js.snap, src/Table/Table.mdx, src/Table/Table.stories.jsx, src/Table/TableCell.scss, src/Table/TableRow.scss
Updated the stickyColumn's box shadow so that it's not too distracting. Also made some updates so that the stickyColumn's bg color matches all the other cells when selected. 
https://user-images.githubusercontent.com/37383785/117375273-7ca3f200-ae83-11eb-8b49-8d5f90751948.mov
=> update stickyColumn shadows and background + add new story

scss/forms/control_button_group.scss, spec/__snapshots__/Storyshots.test.js.snap, src/CheckboxButtonGroup/CheckboxButtonGroup.mdx, src/CheckboxButtonGroup/CheckboxButtonGroup.stories.jsx, src/RadioButton/RadioButton.mdx, src/RadioButton/RadioButton.stories.jsx, src/RadioButtonGroup/RadioButtonGroup.mdx, src/RadioButtonGroup/RadioButtonGroup.stories.jsx, src/index.js
Closes #314 
Add RadioButton and RadioButtonGroup stories to better match the Figma design system. Updated styles to match CheckboxButton recent updates: https://github.com/user-interviews/ui-design-system/pull/295
=> UIDS-314 Update radio button group stories

spec/__snapshots__/Storyshots.test.js.snap, src/Select/CreatableSelect.jsx, src/Select/CreatableSelect.stories.jsx, src/Select/index.js, src/index.js
closes #375 
It was requested that we look into bringing in the `Creatable` component from `react-select` into the Design System. Looks like we have about 4 files in `rails-server` that are making use of it. Was thinking it might be good to have these available as we're doing updates on Selects.
https://react-select.com/creatable
=> feature/UIDS-375 add CreatableSelect into the DS

scss/global.scss, scss/typography.scss, spec/__snapshots__/Storyshots.test.js.snap, stories/Styles/Typography/Typography.stories.jsx
Thought it might be a good idea to check out the Typography updates in the DS first and view all of our components in isolation. 
Might also be helpful to view the Typography page to view all the font side by side. http://localhost:9009/?path=/story/design-system-styles--typography
Would be great to bring to attention any components that might have a font-weight that looks a little heavier than usual. We can always adjust.
=> updates DS typography to use DM Sans

package.json, yarn.lock
Updated on `rails-server` so updating here. Didn't see any issues.
=> upgrade react v16.14.0

src/Tooltip/Tooltip.scss
Seen in one place in the app with the old color
=> HOTFIX update tooltip primary variant to ux-emerald

.github/workflows/percy-nightly-tests.yml
Resolves: #484 
Setting version of node found in package.json
https://github.com/user-interviews/ui-design-system/runs/4403727432?check_suite_focus=true
=> Bug/UIDS-484 Set node version on nightly visual tests

cypress/integration/button_spec.js
=> Chore/ Add Percy snapshots for buttons

.github/workflows/gh-pages-deploy.yml
=> CHORE Fix yaml spacing on deploy action

cypress/integration/steps_spec.js, spec/__snapshots__/Storyshots.test.js.snap, src/Steps/Step.jsx, src/Steps/Step.scss, src/Steps/Steps.jsx, src/Steps/Steps.mdx, src/Steps/Steps.scss, src/Steps/Steps.stories.jsx, src/Steps/index.js, src/index.js
closes #537 
Decided:
- currently set circle size to 2.5rem (40px)
- defaults all colors to $ux-emerald-600
=> add Steps components to DS

spec/__snapshots__/Storyshots.test.js.snap, src/Button/Button.mdx, src/Button/Buttons.stories.jsx
=> Button and Link distinction documentation

scss/buttons.scss, src/Select/styles.js
closes #598 
Applies to all Button variants as well as Dropdown
Applies to all Selects
=> update focus state to Button and Select

spec/__snapshots__/Storyshots.test.js.snap
closes #609 
woops sorry didn't see this wasn't updated when I merged
=> hotfix update snapshot

spec/__snapshots__/Storyshots.test.js.snap, src/FormGroup/FormGroup.jsx, src/FormGroup/FormGroup.mdx, src/FormGroup/FormGroup.stories.jsx
=> add id to FormGroup__invalid-feedback

src/Input/Input.scss
=> update Input focus border to ux-blue-500 for 3:1 contrast ratio

spec/__snapshots__/Storyshots.test.js.snap, src/FormControlLabel/FormControlLabel.jsx
closes #637
Related to Atlassian 1.8 - W3C validator finds WCAG Parsing Accessibility Errors.
This should address these WCAG errors
=> change FormControlLabel label and children to span

scss/colors/inputs.scss
closes #640 
Making some input scss variable updates that will be used on RS.
=> updating input scss variables

cypress/integration/form_elements/checkbox_button_group_spec.js, scss/colors/inputs.scss
This fixes some broken tests due to class name changes and also makes new rgb function work with current node version.
=> Fix cypress tests

.github/workflows/chromatic.yml
=> chromatic change on push develop

src/ToggleInput/ToggleInput.scss
closes #690 
fixes react toggle css import on latest DS release
=> update react toggle css import

spec/__snapshots__/Storyshots.test.js.snap, src/ToggleInput/ToggleInput.scss
=> copy style.css and use directly in ToggleInput

spec/__snapshots__/Storyshots.test.js.snap, src/ToggleInput/ToggleInput.jsx, src/ToggleInput/ToggleInput.mdx, src/ToggleInput/ToggleInput.scss, src/ToggleInput/ToggleInput.stories.jsx
closes #712 
wasn't exposing this story, so putting it here.
https://www.chromatic.com/build?appId=62d040e741710e4f085e0647&number=56
=> add disabled ToggleInput story

src/LoadingOverlay/LoadingOverlay.jsx
=> Adding contentCenterOverflow prop to LoadingOverlay

spec/__snapshots__/Storyshots.test.js.snap, src/Select/SingleSelect.stories.jsx
closes #815 
Adding Grouped Options story for SingleSelect!
=> add Grouped Options story for SingleSelect

src/index.js
closes #830 
Realized I never exported this 🤦‍♂️
=> export Main from DS

.github/workflows/test.yml, .gitignore, README.md, jest.config.js, package.json, spec/__snapshots__/Storyshots.test.js.snap, src/Form/Form.jsx, src/Tabs/__snapshots__/Tabs.test.jsx.snap, src/Toast/__snapshots__/withToast.test.jsx.snap, src/Toast/useToast.js, src/bugsnag.js, src/hoc/withTrackedClick.jsx, src/index.js, yarn.lock
Resolves #844
Add `bugsnag` configuration to DS in order to handle toast arg error. 
If users make a function call to `useToast` with the incorrect arg signature, it will trigger a bugsnag error report.  Eventually we hope to remove this error handling once we are confident we have correctly updated all use cases within `rails-server`.
=> Add bugsnag config to DS and handle toast arg error

src/Accordion/AccordionToggle.scss
closes #846 
💅 
Chromatic: https://62d040e741710e4f085e0647-lpdudvibvn.chromatic.com/?path=/story/components-accordion--default
Design approved ✅ 
https://user-images.githubusercontent.com/37383785/221694506-3b678699-7c72-4343-98fe-c734ecbfe6b2.mov
=> use focus-visible for AccordionToggle focus state

scss/buttons.scss
closes #842 
💅 
Design reviewed ✅  
https://user-images.githubusercontent.com/37383785/218860748-22104c52-6427-49b7-9eb1-7fbaebdd68fb.mov
=> update transparent button active bg color

spec/__snapshots__/Storyshots.test.js.snap, src/Button/Button.jsx, src/Button/Button.scss, src/Button/Buttons.stories.jsx, src/Button/index.js, src/index.js
Reverts user-interviews/ui-design-system#849
Had planned to get this into the next release and working with the Button updates, but working on the Bugsnag v7 update before putting this back in.
=> Revert "Button height updates"

spec/__snapshots__/Storyshots.test.js.snap, src/Button/Button.jsx, src/Button/Button.scss, src/Button/Buttons.stories.jsx, src/Button/index.js, src/index.js
Reverting one more time so that we can remove bugsnag for the release tomorrow 😅 these are button updates that will need to be handled and QA'd on a separate release
Reverts user-interviews/ui-design-system#876
=> Revert "button size updates (previously reverted)"

.github/workflows/test.yml, jest.config.js, package.json, spec/__snapshots__/Storyshots.test.js.snap, src/Toast/useToast.js, src/bugsnag.js, src/index.js, yarn.lock
=> remove Bugsnag

scss/box_shadow.scss, scss/drawer.scss, scss/theme.scss, src/Drawer/Drawer.jsx, src/Drawer/Drawer.mdx, src/Drawer/Drawer.scss, src/Drawer/Drawer.stories.jsx, src/Drawer/DrawerBody.jsx, src/Drawer/DrawerBody.scss, src/Drawer/DrawerFooter.jsx, src/Drawer/DrawerFooter.scss, src/Drawer/DrawerHeader.jsx, src/Drawer/DrawerHeader.scss, src/Drawer/index.js, src/index.js
closes #897
Adds a `Drawer` component and corresponding `DrawerHeader`, `DrawerBody` and `DrawerFooter` child components.
Chromatic: https://www.chromatic.com/build?appId=62d040e741710e4f085e0647&number=221
=> Add drawer component

spec/__snapshots__/Storyshots.test.js.snap, src/Drawer/DrawerFooter.jsx
1. Add isLoading and loadingText props for primary and secondary actions
2. Make order of props and propTypes consistent
=> Add loading props to DrawerFooter actions

package.json, yarn.lock
I tested this locally by running `yarn storybook` and `yarn test`. Let me know if there's something else I should do.
=> Update module resolver to resolve dependabot

src/IconButton/index.js, src/index.js
closes #956 
Forgot to export. 🤦‍♂️ My bad
=> export IconButton

.github/ISSUE_TEMPLATE/-ui-design-system--issue.md
Created a new issues template (borrowed from RX Workflow)
=> Update issue templates

package.json, yarn.lock
Hope this fixes this:
https://github.com/user-interviews/ui-design-system/security/dependabot/99
=> upgrade css-loader

src/Tabs/tabs.module.scss
https://github.com/user-interviews/ui-design-system/assets/3161151/b74044d0-6fb2-4ad6-bce1-710b1d656245
=> Updates Synthesis tab styles

src/Alert/Alert.scss
closes #1078
https://github.com/user-interviews/ui-design-system/assets/37383785/bf06d7e3-e8ad-4486-a88c-817f3a17fd2b
=> Synthesize Alert / Toast colors

src/FormGroup/FormGroup.jsx
[//]: # (
See https://www.notion.so/Expectations-for-Code-Reviews-4c261233caf64f12ab459ba090be2c50 for more best practices around how we do Code Review.
This is a default pull request template that teams can use as a starting point.
You can edit this here: docs/pull_request_template.md
)
Fix https://github.com/user-interviews/ui-design-system/issues/1208
[//]: # (
Provide a brief description of the intent of this pull request.
Example: Allow users to search for a specific product by name.
)
[//]: # (
Indicate who your primary and secondary reviewers are, and make sure they know.
Do this AFTER you have done your own self-review.
)
Primary: @kyleshike 
cc: @jasonbasuil @gabescarbrough 
[//]: # (
Provide a list of the major areas of change or screenshots and provide context that makes it …
=> Show helper text without checking if FormGroup has errors

src/CheckboxButtonGroup/CheckboxButtonGroup.scss
Not sure how this flew under the radar
=> Fixes CheckboxButtonGroup sass imports

src/Select/CreatableSelect.jsx
This was added to the normal select, but we need it on the creatable select as well
=> Adds borderedMultiValue prop to Creatable select

package.json, scss/cards.scss, scss/css_properties.scss, src/Card/Card.scss, src/CardStack/CardStack.scss, src/FlexContainer/FlexContainer.module.css, src/FlexContainer/FlexContainer.stories.tsx, src/FlexContainer/FlexContainer.tsx, src/FlexContainer/index.ts, src/FlexContainer/utils.ts, src/Popover/Popover.scss, src/Popover/PopoverCard.module.scss, src/index.ts, src/ts_module_shims.d.ts
For each breakpoint xs, sm, md, lg, xl, xxl, we provide optional flex props. meaning that for any breakpoint, the following are configurable:
```
alignItems?: 'stretch' | 'center' | 'flex-start' | 'flex-end' | 'baseline' | 'initial' | 'inherit';
flexDirection?: 'column' | 'column-reverse' | 'row' | 'row-reverse';
flexWrap?: 'wrap' | 'no-wrap' | 'wrap-reverse';
justifyContent?: 'flex-start' | 'flex-end' | 'space-between' | 'space-around' | 'space-evenly' | 'center' | 'initial' | 'inherit'
gap?: 1 | 2 | 3 | 4 | 5;
width?: 'xs' | 'sm' | 'md' | 'lg';
```
This props are of course also just available to the component directly to facilitate the most common use case in which breakpoints aren't necessary at all.
=> Adds responsive FlexContainer component

src/RichTextEditor/RichTextEditor.test.tsx, src/RichTextEditor/RichTextEditor.tsx, src/RichTextEditor/RichTextEditorMenuBar.tsx
Fix #1242 
Recording of using new prop 
primary: @kyleshike 
secondary: @gabescarbrough / @jasonbasuil 
https://github.com/user-interviews/ui-design-system/assets/54962889/dddf1778-ef32-4c8e-b508-06fc6e7eeee1
=> Allow RichTextEditor to be read-only

scss/buttons.scss
Demo: https://www.loom.com/share/ef5b38bc922146d38ad3a94e1c3bd39d
=> Fixes active state for buttons

src/Accordion/Accordion.mdx, src/Accordion/Accordion.stories.tsx, src/Accordion/AccordionCollapse.scss, src/Accordion/AccordionCollapse.tsx, src/Accordion/AccordionItem.scss, src/Accordion/AccordionItem.tsx
Adds a new component accordion alert.
=> REC-25 add a new accordion alert component

package.json, yarn.lock
=> upgrade sass-loader v16

package.json
=> Remove packageManager from package.json

.github/workflows/gh-pages-deploy.yml
https://linear.app/user-interviews/issue/REC-296/update-create-new-release-to-handle-gh-pages-deploy-once-during
=> Update github pages workflow to only publish on release

README.md
Updating the README for better organization and readability. Also removes some irrelevant info and hopefully should be easier to consume. Some sections are still WIP but hoping to get those filled in by end of the month with some helpful runbooks.
Open to suggestions for edits or things to include. Looking to make this as helpful as possible, especially for newcomers to the DS.
=> Update README.md for better organization

package.json, yarn.lock
Fixes:
* https://github.com/user-interviews/ui-design-system/security/dependabot/115
* https://github.com/user-interviews/ui-design-system/security/dependabot/112
=> Fix micromatch@4.0.8 and path-to-regexp@^1.9.0 Dependabots

package.json, yarn.lock
https://github.com/user-interviews/ui-design-system/security/dependabot/121
=> fix cookie@0.7.0

package.json, yarn.lock
Fixes dependabot:
https://github.com/user-interviews/ui-design-system/security/dependabot/125
=> update nanoid v3.3.8

yarn.lock
https://github.com/user-interviews/ui-design-system/security/dependabot/128
(make it stop 🥲)
=> Cross-site Scripting (XSS) in serialize-javascript
